spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      password: 123456
      username: root
      url: jdbc:mysql://127.0.0.1:3306/spring_transaction?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
      initial-size: 5
      min-idle: 5
      maxActive: 20
      maxWait: 60000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
mybatis:
  type-aliases-package: com.lee.entity
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl